---
title: "International Rugby Analysis"
output: NA
---



```{r setup}
library(tidyverse)
library(googlesheets4)
library(janitor)
library(lubridate)
library(PlayerRatings)
```

```{r}
my_sheet <-sheets_get("1b2zpxK37lvj-sNvfHkNQboMWPpCTO4FihB_7pEIV45M")

my_sheet
```

```{r}
international_rugby_results <- 
  read_sheet("1b2zpxK37lvj-sNvfHkNQboMWPpCTO4FihB_7pEIV45M",  sheet = "results")

international_rugby_results
```

```{r}
date_indexes 
```


```{r}
get_hyphen_start <- function(x){
  x[1, "start"]
}
```


```{r}
countries_examined <- c("SAF","NZL", "AUS", "ENG", "FRA", "WAL", "IRE", "SCO")
```

FRA	2315	46	32	0	14	5
6	WAL	2288	38	21	0	17	1
7	IRE	2277	36	22	0	14	6
8	ARG	2262	38	20	0	18	15
9	SCO

```{r}
result <- 
  international_rugby_results %>% 
  clean_names() %>% 
  select(match_date = date,
         tourn,
         teams = match,
         score,
         venue) %>% 
  mutate(match_date = dmy(match_date),
         left_team = str_sub(teams, 1, 3),
         right_team = str_sub(teams, -3, -1)) %>% 
  mutate(hyphen_locations = map(score, str_locate, "-"),
         hyphen_start = map_int(hyphen_locations, get_hyphen_start),
         left_team_score = as.integer(str_sub(score, 1, hyphen_start - 1)),
         right_team_score = as.integer(str_sub(score, hyphen_start + 1, -1))) %>% 
  select(-hyphen_locations,
         -hyphen_start,
         -venue,
         -teams,
         -score) %>% 
  filter(left_team != "LIO",
         right_team != "LIO") %>% 
  filter(tourn == "WC",
         match_date > dmy("01/01/1995")) %>% 
  filter(left_team %in% countries_examined,
         right_team %in% countries_examined) %>%
  mutate(binary_result = case_when(
    left_team_score == right_team_score ~ 0.5,
    left_team_score > right_team_score ~ 1,
    left_team_score < right_team_score ~ 0
  )) %>% 
  mutate(game_index = row_number()) %>% 
  nest(everything()) %>% 
  mutate(data_for_elo = map(data, select, game_index, 
                            left_team, 
                            right_team, 
                            binary_result)) %>% 
  mutate(elo_result = map(data_for_elo, elo, history = TRUE, kfac = 40),
         history = map(elo_result, pluck, "history")) 


result
  
```

```{r}
date_indicies <- 
  result %>% 
  pull(data) %>% 
  pluck(1) %>% 
  mutate(date_index = row_number()) %>% 
  select(match_date, date_index)

date_indicies
```


```{r}
result %>% 
  pull(elo_result)
```


```{r}
history_array <- result[[1, "history"]] 

num_countries <- 1:dim(history_array)[1]
num_obs <- 1:dim(history_array)[2]

country_acronyms <- attr(history_array, "dimnames")[[1]]

history_array[num_countries, num_obs,1] %>%
  as_tibble() %>% 
  add_column(country_acronyms,.before = "1") %>% 
  pivot_longer(cols = -country_acronyms) %>% 
  mutate(name = as.integer(name)) %>% 
  rename(time_index = name,
        elo_rating = value) %>% 
  arrange(country_acronyms, time_index) %>% 
  group_by(country_acronyms) %>% 
  mutate(last_elo = lag(elo_rating)) %>% 
  filter(elo_rating != last_elo) %>% 
  filter(country_acronyms %in% countries_examined) %>% 
  left_join(date_indicies,
            by = c("time_index" = "date_index")) %>% 
  ggplot(aes(x = match_date, 
             y = elo_rating,
             color = country_acronyms)) +
  geom_point() +
  geom_smooth(se = F) +
  facet_wrap(facets = vars(country_acronyms))
```

